// Generated by dia2code
#ifndef SERVER__SERVICEEXCEPTION__H
#define SERVER__SERVICEEXCEPTION__H

#include <string>

namespace server {

  /// class ServiceException - 
  class ServiceException {
    // Attributes
  protected:
    int _status;
    std::string msg;
    // Operations
  public:
    ServiceException (int status, std::string msg);
    int status () const;
    const char* what () const;
  };

};

#endif
