// Generated by dia2code
#ifndef SERVER__SERVER__H
#define SERVER__SERVER__H

#include <vector>
#include <memory>

namespace state {
  class Game;
};
namespace engine {
  class Engine;
  class Command;
}

#include "state/Game.h"
#include "engine/Engine.h"
#include "ServerState.h"
#include "engine/Command.h"

namespace server {

  /// class Server - 
  class Server {
    // Associations
    // Attributes
  private:
    std::vector< std::shared_ptr<engine::Command> > history;
    std::shared_ptr<state::Game> game;
    std::shared_ptr<engine::Engine> engine;
    ServerState state;
    unsigned int joinedPlayers;
    // Operations
  public:
    Server ();
    void run ();
  private:
    void pushCommand (std::shared_ptr<engine::Command> command);
    std::vector< std::shared_ptr<engine::Command> > getCommands (unsigned int from) const;
    void createGame (unsigned int numPlayers);
  };

};

#endif
