// Generated by dia2code
#ifndef SERVER__SERVERSTATE__H
#define SERVER__SERVERSTATE__H


namespace server {

  enum ServerState {
    STATE_IDLE     = 0,
    STATE_INIT     = 1,
    STATE_GAME     = 2
  };

};

#endif
