// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H

#include <vector>
#include <string>

namespace engine {
  class Interaction;
};
namespace state {
  class Game;
};
namespace engine {
  class Command;
  class Engine;
}

#include "Interaction.h"
#include "Command.h"
#include "Engine.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Associations
    // Attributes
  private:
    std::vector<Interaction> interactions;
    // Operations
  public:
    AttackCommand (unsigned int playerId, std::vector<Interaction> interactions);
    std::string toString () const;
    bool isAllowed (state::Game& game) const;
    void execute (state::Game& game);
    std::vector<Interaction> getInteractions () const;
  };

};

#endif
