// Generated by dia2code
#ifndef ENGINE__CHOICECOMMAND__H
#define ENGINE__CHOICECOMMAND__H

#include <string>

namespace state {
  class Game;
};
namespace engine {
  class Command;
  class Engine;
}

#include "CommandType.h"
#include "Command.h"
#include "Engine.h"

namespace engine {

  /// class ChoiceCommand - 
  class ChoiceCommand : public engine::Command {
    // Attributes
  private:
    unsigned int landId;
    // Operations
  public:
    ChoiceCommand (CommandType type, unsigned int playerId, unsigned int landId);
    std::string toString () const;
    bool isAllowed (state::Game& game) const;
    void execute (state::Game& game);
    unsigned int getLandId () const;
    void rollback (state::Game& game);
    std::string toJSON () const;
  };

};

#endif
