// Generated by dia2code
#ifndef ENGINE__COMMANDTYPE__H
#define ENGINE__COMMANDTYPE__H


namespace engine {

  enum CommandType {
    COMMAND_CHOOSE_HEADQUARTERS     = 0,
    COMMAND_CHOOSE_REINFORCEMENT     = 1,
    COMMAND_BUILD_PORT     = 2,
    COMMAND_SKIP_ROUND     = 3,
    COMMAND_ABANDON     = 4,
    COMMAND_ATTACK     = 5,
    COMMAND_MOVE     = 6,
    COMMAND_USE_ITEM     = 7
  };

};

#endif
