// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <string>

#include "CommandType.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Attributes
  public:
    CommandType type;
    int playerId;
    int landOneId;
    int landTwoId;
    // Operations
  public:
    Command (CommandType type, int playerId, int landOneId, int landTwoId);
    std::string toString () const;
  };

};

#endif
