// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <string>

namespace state {
  class Game;
}

#include "CommandType.h"
#include "state/Game.h"

namespace engine {

  // abstract
  /// class Command - 
  class Command {
    // Associations
    // Attributes
  protected:
    CommandType type;
    unsigned int playerId;
    bool executed;
    // Operations
  public:
    virtual std::string toString () const = 0;
    virtual bool isAllowed (state::Game& game) const = 0;
    /// 																																														
    /// @param game		(???) 
    virtual void execute (state::Game& game) = 0;
    virtual void rollback (state::Game& game) = 0;
    CommandType getType () const;
    unsigned int getPlayerId () const;
  };

};

#endif
