// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <mutex>
#include <queue>
#include <memory>
#include <map>

namespace state {
  class Game;
};
namespace engine {
  class Engine;
  class Command;
};
namespace ai {
  class AI;
};
namespace engine {
  class MoveCommand;
  class AttackCommand;
  class ChoiceCommand;
  class ActionCommand;
}

#include "state/Game.h"
#include "Command.h"
#include "ai/AI.h"
#include "MoveCommand.h"
#include "AttackCommand.h"
#include "ChoiceCommand.h"
#include "ActionCommand.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  public:
    bool commandQuit;
    std::mutex mutex;
  private:
    std::queue< std::shared_ptr<Command> > commandQueue;
    std::shared_ptr<state::Game> game;
    std::map<unsigned int, std::shared_ptr<ai::AI>> aiPlayers;
    // Operations
  public:
    Engine (std::shared_ptr<state::Game> game);
    Engine (Engine& engine);
    void pushCommand (std::shared_ptr<Command> command);
    void flushCommands ();
    bool isAllowed (std::shared_ptr<Command> command);
    void registerAIPlayer (unsigned int playerId, std::shared_ptr<ai::AI> ai);
    void operator() ();
  private:
    void execute (std::shared_ptr<Command> command);
  };

};

#endif
