// Generated by dia2code
#ifndef ENGINE__INTERACTION__H
#define ENGINE__INTERACTION__H


namespace engine {

  /// class Interaction - 
  class Interaction {
    // Attributes
  public:
    unsigned int landOneId;
    unsigned int landTwoId;
    // Operations
  public:
    Interaction (unsigned int landOneId = 0, unsigned int landTwoId = 0);
  };

};

#endif
