// Generated by dia2code
#ifndef RENDER__CLIENT__H
#define RENDER__CLIENT__H

#include <vector>
#include <memory>

namespace state {
  class Land;
  class Game;
};
namespace engine {
  class Engine;
};
namespace render {
  class Client;
};
namespace engine {
  class Command;
};
namespace state {
  class Player;
};
namespace render {
  class Renderer;
}

#include "state/Land.h"
#include "state/Game.h"
#include "engine/Engine.h"
#include "engine/Command.h"
#include "state/Player.h"
#include "Renderer.h"

namespace render {

  /// class Client - 
  class Client {
    // Attributes
  private:
    std::vector<unsigned int> attributedPlayers;
    unsigned int currentPlayerId;
    std::shared_ptr<state::Land> selectedInfoLand;
    std::shared_ptr<state::Land> selectedLand;
    bool debugMode;
    std::shared_ptr<state::Game> game;
    std::shared_ptr<engine::Engine> engine;
    // Operations
  public:
    Client (std::shared_ptr<state::Game> game, std::shared_ptr<engine::Engine> engine);
    Client (Client& client);
    ~Client ();
    std::vector<unsigned int> getAttributedPlayers () const;
    void addAttributedPlayer (unsigned int playerId);
    unsigned int getCurrentPlayerId () const;
    std::shared_ptr<state::Land> getSelectedInfoLand () const;
    void setSelectedInfoLand (std::shared_ptr<state::Land> land);
    std::shared_ptr<state::Land> getSelectedLand () const;
    void setSelectedLand (std::shared_ptr<state::Land> land);
    bool getDebugMode () const;
    void operator() ();
  private:
    void sendCommand (std::shared_ptr<engine::Command> command);
  };

};

#endif
