// Generated by dia2code
#ifndef RENDER__RENDERER__H
#define RENDER__RENDERER__H

#include <map>
#include <SFML/Graphics.hpp>

namespace render {
  class Renderer;
}


namespace render {

  /// class Renderer - 
  class Renderer {
    // Associations
    // Attributes
  private:
    std::map<state::LandType, sf::Texture> landTextures;
    sf::Font font;
    // Operations
  public:
    ~Renderer ();
    static Renderer& getInstance ();
    void render (sf::RenderWindow& window);
    void init ();
  private:
    Renderer ();
    void loadTextures ();
  };

};

#endif
