// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <memory>

namespace state {
  class Player;
  class Game;
};
namespace engine {
  class Engine;
}

#include "state/Player.h"
#include "state/Game.h"
#include "engine/Engine.h"

namespace ai {

  // abstract
  /// class AI - 
  class AI {
    // Attributes
  protected:
    std::shared_ptr<state::Player> player;
    // Operations
  public:
    AI (std::shared_ptr<state::Player> player);
    virtual void run (std::shared_ptr<state::Game> game, std::shared_ptr<engine::Engine> engine) = 0;
  };

};

#endif
