// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <memory>
#include <vector>

namespace state {
  class Game;
  class Player;
};
namespace engine {
  class Engine;
}

#include "state/Game.h"
#include "state/Player.h"
#include "engine/Engine.h"

namespace ai {

  // abstract
  /// class AI - 
  class AI {
    // Attributes
  protected:
    unsigned int playerId;
    // Operations
  public:
    AI (unsigned int playerId);
    virtual std::shared_ptr<engine::Command> run (std::shared_ptr<state::Game> game) = 0;
    std::vector<std::shared_ptr<engine::Command>> getPossibilities (std::shared_ptr<state::Game> game, unsigned int playerId);
  };

};

#endif
