// Generated by dia2code
#ifndef AI__DUMBAI__H
#define AI__DUMBAI__H

#include <memory>

namespace state {
  class Game;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "state/Game.h"
#include "engine/Engine.h"
#include "AI.h"

namespace ai {

  /// class DumbAI - 
  class DumbAI : public ai::AI {
    // Operations
  public:
    DumbAI (unsigned int playerId);
    virtual void  run (std::shared_ptr<state::Game> game, std::shared_ptr<engine::Engine> engine);
  };

};

#endif
