// Generated by dia2code
#ifndef AI__DUMBAI__H
#define AI__DUMBAI__H

#include <memory>

namespace state {
  class Game;
};
namespace ai {
  class AI;
}

#include "state/Game.h"
#include "AI.h"

namespace ai {

  /// class DumbAI - 
  class DumbAI : public ai::AI {
    // Operations
  public:
    DumbAI (unsigned int playerId);
    virtual std::shared_ptr<engine::Command> run (std::shared_ptr<state::Game> game);
  };

};

#endif
