// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H

#include <SFML/Graphics.hpp>
#include <memory>

namespace state {
  class Land;
}

#include "Land.h"

namespace state {

  /// class Cell - 
  class Cell {
    // Attributes
  public:
    sf::Vector2u position;
    std::shared_ptr<Land> land;
    // Operations
  public:
    Cell ();
  };

};

#endif
