// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H

#include <memory>

namespace state {
  class Land;
}

#include "Land.h"

namespace state {

  /// class Cell - 
  class Cell {
    // Attributes
  public:
    sf::Vector2u position;
    bool borderTop;
    bool borderBottom;
    bool borderLeft;
    bool borderRight;
    std::shared_ptr<Land> land;
    // Operations
  public:
    /// 	
    /// @param position		(???) 
    /// @param borderTop		(???) 
    /// @param borderBottom		(???) 
    /// @param borderLeft		(???) 
    /// @param borderRight		(???) 
    /// @param land		(???) 
    Cell (sf::Vector2u position, bool borderTop, bool borderBottom, bool borderLeft, bool borderRight, std::shared_ptr<Land> land);
  };

};

#endif
