// Generated by dia2code
#ifndef STATE__CONNECTIONTYPE__H
#define STATE__CONNECTIONTYPE__H


namespace state {

  enum ConnectionType {
    CONNECTION_NONE     = 0,
    CONNECTION_WATER     = 1,
    CONNECTION_LAND     = 2
  };

};

#endif
