// Generated by dia2code
#ifndef STATE__LANDTYPE__H
#define STATE__LANDTYPE__H


namespace state {

  enum LandType {
    LAND_NONE = 0,
    LAND_DESERT = 1,
    LAND_FOREST = 2,
    LAND_MOUNTAIN = 3,
    LAND_COASTAL = 4,
    LAND_MEADOW = 5
  };

};

#endif
