// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <memory>
#include <SFML/Graphics.hpp>

namespace state {
  class Land;
  class Player;
}

#include "Land.h"
#include "ItemType.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  private:
    unsigned int id;
    /// 		
    std::shared_ptr<Land> headquarters;
    std::shared_ptr<Land> heroPosition;
    bool deadHero;
    bool alive;
    ItemType storedItem;
    sf::Color color;
    // Operations
  public:
    Player (unsigned int id, sf::Color color);
    Player (std::shared_ptr<Player> toCopy);
    ~Player ();
    unsigned int getId () const;
    std::shared_ptr<Land> getHeadquarters () const;
    void setHeadquarters (std::shared_ptr<Land> headquarters);
    std::shared_ptr<Land> getHeroPosition () const;
    void setHeroPosition (std::shared_ptr<Land> heroPosition);
    bool getDeadHero () const;
    void setDeadHero (bool deadHero);
    bool isAlive () const;
    void setAlive (bool alive);
    ItemType getStoredItem () const;
    void setStoredItem (ItemType storedItem);
    sf::Color getColor () const;
    Json::Value toJSON () const;
  };

};

#endif
