// Generated by dia2code
#ifndef STATE__STEP__H
#define STATE__STEP__H


namespace state {

  enum Step {
    STEP_REINFORCEMENT     = 1,
    STEP_ACTION     = 2,
    STEP_MOVING     = 3
  };

};

#endif
