// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandType.h"
#include "engine/Command.h"
#include "engine/Interaction.h"
#include "engine/MoveCommand.h"
#include "engine/AttackCommand.h"
#include "engine/ChoiceCommand.h"
#include "engine/ActionCommand.h"
#include "engine/Engine.h"
#endif
