// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <memory>

namespace state {
  class Game;
};
namespace render {
  class Client;
};
namespace engine {
  class Engine;
  class Command;
}

#include "state/Game.h"
#include "render/Client.h"
#include "engine/Engine.h"
#include "engine/Command.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  private:
    std::shared_ptr<state::Game> game;
    std::shared_ptr<render::Client> gui;
    std::shared_ptr<engine::Engine> engine;
    int nextCommandIndex;
    // Operations
  public:
    Client ();
    void run ();
    int requestGetStatus ();
    int requestCreateGame (unsigned int numPlayers);
    int requestPushCommand (std::shared_ptr<engine::Command> command);
    int requestGetCommands ();
  };

};

#endif
